spring:
    datasource:
        url: jdbc:mysql://localhost:3306/message?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: Shashi29

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 